#############################################################################
# Makefile for building: Piano1.app/Contents/MacOS/Piano1
# Generated by qmake (2.01a) (Qt 4.7.4) on: Thu Apr 18 15:49:08 2013
# Project:  Piano1.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/local/Qt4.7/mkspecs/macx-g++ CONFIG+=x86_64 -o Makefile Piano1.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Qt4.7/mkspecs/macx-g++ -I. -I/Library/Frameworks/QtCore.framework/Versions/4/Headers -I/usr/include/QtCore -I/Library/Frameworks/QtGui.framework/Versions/4/Headers -I/usr/include/QtGui -I/usr/include -I. -I. -I. -F/Library/Frameworks
LINK          = g++
LFLAGS        = -headerpad_max_install_names -all_load -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5
LIBS          = $(SUBLIBS) -F/Library/Frameworks -L/Library/Frameworks -framework QtGui -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		pianWHOA.cpp \
		tutormenu.cpp \
		begin.cpp \
		zeldatutor.cpp \
		twinkletutor.cpp \
		happytutor.cpp \
		rowtutor.cpp \
		hottutor.cpp moc_pianWHOA.cpp \
		moc_tutormenu.cpp \
		moc_begin.cpp \
		moc_zeldatutor.cpp \
		moc_twinkletutor.cpp \
		moc_happytutor.cpp \
		moc_rowtutor.cpp \
		moc_hottutor.cpp
OBJECTS       = main.o \
		pianWHOA.o \
		tutormenu.o \
		begin.o \
		zeldatutor.o \
		twinkletutor.o \
		happytutor.o \
		rowtutor.o \
		hottutor.o \
		moc_pianWHOA.o \
		moc_tutormenu.o \
		moc_begin.o \
		moc_zeldatutor.o \
		moc_twinkletutor.o \
		moc_happytutor.o \
		moc_rowtutor.o \
		moc_hottutor.o
DIST          = /usr/local/Qt4.7/mkspecs/common/unix.conf \
		/usr/local/Qt4.7/mkspecs/common/mac.conf \
		/usr/local/Qt4.7/mkspecs/common/mac-g++.conf \
		/usr/local/Qt4.7/mkspecs/qconfig.pri \
		/usr/local/Qt4.7/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Qt4.7/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.7/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.7/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.7/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Qt4.7/mkspecs/features/debug.prf \
		/usr/local/Qt4.7/mkspecs/features/default_post.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.7/mkspecs/features/staticlib.prf \
		/usr/local/Qt4.7/mkspecs/features/static.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/x86_64.prf \
		/usr/local/Qt4.7/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.7/mkspecs/features/qt.prf \
		/usr/local/Qt4.7/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.7/mkspecs/features/moc.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.7/mkspecs/features/resources.prf \
		/usr/local/Qt4.7/mkspecs/features/uic.prf \
		/usr/local/Qt4.7/mkspecs/features/yacc.prf \
		/usr/local/Qt4.7/mkspecs/features/lex.prf \
		/usr/local/Qt4.7/mkspecs/features/include_source_dir.prf \
		Piano1.pro
QMAKE_TARGET  = Piano1
DESTDIR       = 
TARGET        = Piano1.app/Contents/MacOS/Piano1

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-gdwarf-2 \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.5 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile Piano1.app/Contents/PkgInfo Piano1.app/Contents/Resources/empty.lproj Piano1.app/Contents/Info.plist $(TARGET)

$(TARGET): ui_pianWHOA.h ui_tutormenu.h ui_begin.h ui_zeldatutor.h ui_twinkletutor.h ui_happytutor.h ui_rowtutor.h ui_hottutor.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) Piano1.app/Contents/MacOS/ || $(MKDIR) Piano1.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Piano1.pro  /usr/local/Qt4.7/mkspecs/macx-g++/qmake.conf /usr/local/Qt4.7/mkspecs/common/unix.conf \
		/usr/local/Qt4.7/mkspecs/common/mac.conf \
		/usr/local/Qt4.7/mkspecs/common/mac-g++.conf \
		/usr/local/Qt4.7/mkspecs/qconfig.pri \
		/usr/local/Qt4.7/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Qt4.7/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.7/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.7/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.7/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Qt4.7/mkspecs/features/debug.prf \
		/usr/local/Qt4.7/mkspecs/features/default_post.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.7/mkspecs/features/staticlib.prf \
		/usr/local/Qt4.7/mkspecs/features/static.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/x86_64.prf \
		/usr/local/Qt4.7/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.7/mkspecs/features/qt.prf \
		/usr/local/Qt4.7/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.7/mkspecs/features/moc.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.7/mkspecs/features/resources.prf \
		/usr/local/Qt4.7/mkspecs/features/uic.prf \
		/usr/local/Qt4.7/mkspecs/features/yacc.prf \
		/usr/local/Qt4.7/mkspecs/features/lex.prf \
		/usr/local/Qt4.7/mkspecs/features/include_source_dir.prf \
		/Library/Frameworks/QtGui.framework/QtGui.prl \
		/Library/Frameworks/QtCore.framework/QtCore.prl
	$(QMAKE) -spec /usr/local/Qt4.7/mkspecs/macx-g++ CONFIG+=x86_64 -o Makefile Piano1.pro
/usr/local/Qt4.7/mkspecs/common/unix.conf:
/usr/local/Qt4.7/mkspecs/common/mac.conf:
/usr/local/Qt4.7/mkspecs/common/mac-g++.conf:
/usr/local/Qt4.7/mkspecs/qconfig.pri:
/usr/local/Qt4.7/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Qt4.7/mkspecs/features/qt_functions.prf:
/usr/local/Qt4.7/mkspecs/features/qt_config.prf:
/usr/local/Qt4.7/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt4.7/mkspecs/features/default_pre.prf:
/usr/local/Qt4.7/mkspecs/features/mac/default_pre.prf:
/usr/local/Qt4.7/mkspecs/features/mac/dwarf2.prf:
/usr/local/Qt4.7/mkspecs/features/debug.prf:
/usr/local/Qt4.7/mkspecs/features/default_post.prf:
/usr/local/Qt4.7/mkspecs/features/mac/default_post.prf:
/usr/local/Qt4.7/mkspecs/features/mac/objective_c.prf:
/usr/local/Qt4.7/mkspecs/features/staticlib.prf:
/usr/local/Qt4.7/mkspecs/features/static.prf:
/usr/local/Qt4.7/mkspecs/features/mac/x86_64.prf:
/usr/local/Qt4.7/mkspecs/features/warn_on.prf:
/usr/local/Qt4.7/mkspecs/features/qt.prf:
/usr/local/Qt4.7/mkspecs/features/unix/thread.prf:
/usr/local/Qt4.7/mkspecs/features/moc.prf:
/usr/local/Qt4.7/mkspecs/features/mac/rez.prf:
/usr/local/Qt4.7/mkspecs/features/mac/sdk.prf:
/usr/local/Qt4.7/mkspecs/features/resources.prf:
/usr/local/Qt4.7/mkspecs/features/uic.prf:
/usr/local/Qt4.7/mkspecs/features/yacc.prf:
/usr/local/Qt4.7/mkspecs/features/lex.prf:
/usr/local/Qt4.7/mkspecs/features/include_source_dir.prf:
/Library/Frameworks/QtGui.framework/QtGui.prl:
/Library/Frameworks/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Qt4.7/mkspecs/macx-g++ CONFIG+=x86_64 -o Makefile Piano1.pro

Piano1.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) Piano1.app/Contents || $(MKDIR) Piano1.app/Contents 
	@$(DEL_FILE) Piano1.app/Contents/PkgInfo
	@echo "APPL????" >Piano1.app/Contents/PkgInfo
Piano1.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) Piano1.app/Contents/Resources || $(MKDIR) Piano1.app/Contents/Resources 
	@touch Piano1.app/Contents/Resources/empty.lproj
	
Piano1.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) Piano1.app/Contents || $(MKDIR) Piano1.app/Contents 
	@$(DEL_FILE) Piano1.app/Contents/Info.plist
	@sed -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,Piano1,g" -e "s,@TYPEINFO@,????,g" /usr/local/Qt4.7/mkspecs/macx-g++/Info.plist.app >Piano1.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/Piano11.0.0 || $(MKDIR) .tmp/Piano11.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Piano11.0.0/ && $(COPY_FILE) --parents pianWHOA.h tutormenu.h begin.h zeldatutor.h twinkletutor.h happytutor.h rowtutor.h hottutor.h pianWHOA.h .tmp/Piano11.0.0/ && $(COPY_FILE) --parents main.cpp pianWHOA.cpp tutormenu.cpp begin.cpp zeldatutor.cpp twinkletutor.cpp happytutor.cpp rowtutor.cpp hottutor.cpp .tmp/Piano11.0.0/ && $(COPY_FILE) --parents pianWHOA.ui tutormenu.ui begin.ui zeldatutor.ui twinkletutor.ui happytutor.ui rowtutor.ui hottutor.ui pianWHOA.ui .tmp/Piano11.0.0/ && (cd `dirname .tmp/Piano11.0.0` && $(TAR) Piano11.0.0.tar Piano11.0.0 && $(COMPRESS) Piano11.0.0.tar) && $(MOVE) `dirname .tmp/Piano11.0.0`/Piano11.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Piano11.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r Piano1.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_pianWHOA.cpp moc_tutormenu.cpp moc_begin.cpp moc_zeldatutor.cpp moc_twinkletutor.cpp moc_happytutor.cpp moc_rowtutor.cpp moc_hottutor.cpp moc_pianWHOA.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_pianWHOA.cpp moc_tutormenu.cpp moc_begin.cpp moc_zeldatutor.cpp moc_twinkletutor.cpp moc_happytutor.cpp moc_rowtutor.cpp moc_hottutor.cpp moc_pianWHOA.cpp
moc_pianWHOA.cpp: ui_pianWHOA.h \
		pianWHOA.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ pianWHOA.h -o moc_pianWHOA.cpp

moc_tutormenu.cpp: tutormenu.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ tutormenu.h -o moc_tutormenu.cpp

moc_begin.cpp: begin.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ begin.h -o moc_begin.cpp

moc_zeldatutor.cpp: ui_zeldatutor.h \
		tutormenu.h \
		zeldatutor.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ zeldatutor.h -o moc_zeldatutor.cpp

moc_twinkletutor.cpp: ui_twinkletutor.h \
		tutormenu.h \
		twinkletutor.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ twinkletutor.h -o moc_twinkletutor.cpp

moc_happytutor.cpp: ui_happytutor.h \
		tutormenu.h \
		happytutor.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ happytutor.h -o moc_happytutor.cpp

moc_rowtutor.cpp: ui_rowtutor.h \
		tutormenu.h \
		rowtutor.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ rowtutor.h -o moc_rowtutor.cpp

moc_hottutor.cpp: ui_hottutor.h \
		tutormenu.h \
		hottutor.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ hottutor.h -o moc_hottutor.cpp

moc_pianWHOA.cpp: ui_pianWHOA.h \
		pianWHOA.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ pianWHOA.h -o moc_pianWHOA.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all: ui_pianWHOA.h ui_tutormenu.h ui_begin.h ui_zeldatutor.h ui_twinkletutor.h ui_happytutor.h ui_rowtutor.h ui_hottutor.h ui_pianWHOA.h
compiler_uic_clean:
	-$(DEL_FILE) ui_pianWHOA.h ui_tutormenu.h ui_begin.h ui_zeldatutor.h ui_twinkletutor.h ui_happytutor.h ui_rowtutor.h ui_hottutor.h ui_pianWHOA.h
ui_pianWHOA.h: pianWHOA.ui
	/Developer/Tools/Qt/uic pianWHOA.ui -o ui_pianWHOA.h

ui_tutormenu.h: tutormenu.ui
	/Developer/Tools/Qt/uic tutormenu.ui -o ui_tutormenu.h

ui_begin.h: begin.ui
	/Developer/Tools/Qt/uic begin.ui -o ui_begin.h

ui_zeldatutor.h: zeldatutor.ui
	/Developer/Tools/Qt/uic zeldatutor.ui -o ui_zeldatutor.h

ui_twinkletutor.h: twinkletutor.ui
	/Developer/Tools/Qt/uic twinkletutor.ui -o ui_twinkletutor.h

ui_happytutor.h: happytutor.ui
	/Developer/Tools/Qt/uic happytutor.ui -o ui_happytutor.h

ui_rowtutor.h: rowtutor.ui
	/Developer/Tools/Qt/uic rowtutor.ui -o ui_rowtutor.h

ui_hottutor.h: hottutor.ui
	/Developer/Tools/Qt/uic hottutor.ui -o ui_hottutor.h

ui_pianWHOA.h: pianWHOA.ui
	/Developer/Tools/Qt/uic pianWHOA.ui -o ui_pianWHOA.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp tutormenu.h \
		begin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

pianWHOA.o: pianWHOA.cpp pianWHOA.h \
		ui_pianWHOA.h \
		tutormenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pianWHOA.o pianWHOA.cpp

tutormenu.o: tutormenu.cpp tutormenu.h \
		ui_tutormenu.h \
		zeldatutor.h \
		ui_zeldatutor.h \
		hottutor.h \
		ui_hottutor.h \
		twinkletutor.h \
		ui_twinkletutor.h \
		rowtutor.h \
		ui_rowtutor.h \
		happytutor.h \
		ui_happytutor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tutormenu.o tutormenu.cpp

begin.o: begin.cpp begin.h \
		ui_begin.h \
		tutormenu.h \
		pianWHOA.h \
		ui_pianWHOA.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o begin.o begin.cpp

zeldatutor.o: zeldatutor.cpp zeldatutor.h \
		ui_zeldatutor.h \
		tutormenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o zeldatutor.o zeldatutor.cpp

twinkletutor.o: twinkletutor.cpp twinkletutor.h \
		ui_twinkletutor.h \
		tutormenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o twinkletutor.o twinkletutor.cpp

happytutor.o: happytutor.cpp happytutor.h \
		ui_happytutor.h \
		tutormenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o happytutor.o happytutor.cpp

rowtutor.o: rowtutor.cpp rowtutor.h \
		ui_rowtutor.h \
		tutormenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rowtutor.o rowtutor.cpp

hottutor.o: hottutor.cpp hottutor.h \
		ui_hottutor.h \
		tutormenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hottutor.o hottutor.cpp

moc_pianWHOA.o: moc_pianWHOA.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pianWHOA.o moc_pianWHOA.cpp

moc_tutormenu.o: moc_tutormenu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tutormenu.o moc_tutormenu.cpp

moc_begin.o: moc_begin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_begin.o moc_begin.cpp

moc_zeldatutor.o: moc_zeldatutor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_zeldatutor.o moc_zeldatutor.cpp

moc_twinkletutor.o: moc_twinkletutor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_twinkletutor.o moc_twinkletutor.cpp

moc_happytutor.o: moc_happytutor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_happytutor.o moc_happytutor.cpp

moc_rowtutor.o: moc_rowtutor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rowtutor.o moc_rowtutor.cpp

moc_hottutor.o: moc_hottutor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_hottutor.o moc_hottutor.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

